### ISSUE TITLE
Đorđe Jovanović (Ђорђе Јовановић) - SER (Serbia)

### ISSUE THREAD

**Issue by TheRealVladimirLemon** [Kaiserreich/Kaiserreich-Research-Assistance-Programme#16]
There are multiple historical figures by this name, we are specifically looking for the Serbian general who was a partisan IRL: https://sl.m.wikipedia.org/wiki/%C4%90or%C4%91e_Jovanovi%C4%87_(general)

We currently have no known pictures. Anything is welcome.

**Comment by LvovMsk** [comment]
![изображение](https://github.com/Kaiserreich/Kaiserreich-Research-Assistance-Programme/assets/104763828/2fb6664b-7b46-4147-9bed-28f76b5bf09f)

Resource: https://www.geni.com/people/Djordje-Jovanovic/6000000002469861066
The man in the photo is wearing an Italian uniform. Although this general was in Italian captivity, there is no information about his collaboration. And by this time he would have been 50-55 years old, but in the photo the person looks younger. So, the source is not completely reliable.

**Comment by TheRealVladimirLemon** [comment]
> ![изображение](https://private-user-images.githubusercontent.com/104763828/314619097-2fb6664b-7b46-4147-9bed-28f76b5bf09f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5NjE2MjgsIm5iZiI6MTcxMDk2MTMyOCwicGF0aCI6Ii8xMDQ3NjM4MjgvMzE0NjE5MDk3LTJmYjY2NjRiLTdiNDYtNDE0Ny05YmVkLTI4Zjc2YjViZjA5Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMFQxOTAyMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZGZjOWI5ZGU2NTAyZmRmZjQ4ZDYzNzk1OWI4NjJjZjU0NTA3ZGU5NGE3NmMxYTkyNTVkMTRlZWU5YjU1NWU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eVErTVEGqUoLuLyzIeKR3AYExoF1hk-FCP5JVQl-TAk)
> 
> Resource: https://www.geni.com/people/Djordje-Jovanovic/6000000002469861066 The man in the photo is wearing an Italian uniform. Although this general was in Italian captivity, there is no information about his collaboration. And by this time he would have been 50-55 years old, but in the photo the person looks younger. So, the source is not completely reliable.

This is, in-fact, a Yugoslav uniform from the kingdom of Yugoslavia. 

King Peter II can be seen wearing it here: 
![king-peter-of-yugoslavia-1942-peter-ii-of-yugoslavia-1923-1970-also-DYF1E2](https://github.com/Kaiserreich/Kaiserreich-Research-Assistance-Programme/assets/90009369/f972e6c4-a1ce-4696-a29c-0b437c0a3148)
