### ISSUE TITLE
Sekarmadji Maridjan Kartosoewirjo - INS (Insulindia)

### ISSUE THREAD

**Issue by Blackleafx** [Kaiserreich/Kaiserreich-Research-Assistance-Programme#25]
Also spelled "Menjelang Eksekusi Kartosuwiryo" in some sources. This guy is the current Islamist leader of Insulindia but the portrait we use is from a photo taken of him in the 50s or 60s, close to his execution. 
![image](https://github.com/Kaiserreich/Kaiserreich-Research-Assistance-Programme/assets/42992351/38eb6597-fdda-4e2c-bd88-cf592c419fed)

Only a handful of younger images of him exist. There is this from 1950 
![image](https://github.com/Kaiserreich/Kaiserreich-Research-Assistance-Programme/assets/42992351/c52d7497-0462-431a-a97b-5e9c87d9fed3)
and this which is probably even younger and currently seems like our best shot. If you can get a hold of a higher quality version of it or a similar young pic of him, that would be wonderful.
![image](https://github.com/Kaiserreich/Kaiserreich-Research-Assistance-Programme/assets/42992351/7f9326a6-97a0-47fb-af85-da51094dc05e)

Take note that despite the caption, this photo is NOT him, it is a mislabelled image of Tan Malaka. 
![image](https://github.com/Kaiserreich/Kaiserreich-Research-Assistance-Programme/assets/42992351/9c8493f0-73d6-4fd5-b995-75a4d1857aac)

**Comment by Ighloa** [comment]
Found an undated image of a young Kartosuwiryo on Indonesia's National Library website. The quality is not the best I do admit, but I nevertheless wanted to submit it in case it can be of any help. I'll continue looking for something of better quality.

![606469](https://github.com/Kaiserreich/Kaiserreich-Research-Assistance-Programme/assets/73202949/a567e04d-1fa5-4cd4-9ba0-8d3ce709154c)

https://opac.perpusnas.go.id/DetailOpac.aspx?id=606469

**Comment by Blackleafx** [comment]
At the very least anything that gives us a better idea of what he "looked" like, hair, face, head shape etc, is still helpful, so thank you!

**Comment by IndomieEnjoyer** [comment]
Found two images of him from "Darul Islam - NII dan Kartosuwirjo" by Holk H. Dengel

![SM Kartosuwirjo (1929)](https://github.com/Kaiserreich/Kaiserreich-Research-Assistance-Programme/assets/160296252/851b8984-f63d-450f-afb7-01caef5fc94a)
From 1929

![SM Kartosuwirjo (1938)](https://github.com/Kaiserreich/Kaiserreich-Research-Assistance-Programme/assets/160296252/01c8c9a0-c071-432f-8935-e56218c1744c)
From 1938 (third from left)

**Comment by Blackleafx** [comment]
Thank you, will forward this to the rest of the team.
