### ISSUE TITLE
Georgios Papandreou - GRE (Greece/Third Hellenic Republic)

### ISSUE THREAD

**Issue by mpekios723** [Kaiserreich/Kaiserreich-Research-Assistance-Programme#32]
![ΠΑΠΑΝΔΡΕΟΥ](https://github.com/Kaiserreich/Kaiserreich-Research-Assistance-Programme/assets/118221186/f6a5794c-5e18-4a2e-a464-c96054d9fad6)

BORN: 13th February, 1888

One of Greece's most influental political figures, Papandreou was born in the village of Kalentzi in the Achaea Region, he grew up in an abusive household with his father and his one brother and sister, his father a severe alcohol addict and used to physically abuse Papandreou as a child, as a result Papandreou would escape his household by the age of 13, his older brother known as Nikos Papandreou who was seven years older than him, had resorted in Athens and started his own life by working in construction, Papandreou after escaping from his abusive household, would finally go to Athens after living six months in the streets, once arriving in Athens, he would meet his older brother and he would begin working on construction and begin school, which he would finish by the Age of 19, as he had to do extra class due to his one year absence from it, he would stop working in construction and invest the money he collected by the years to go to the Polytechnic University, on which he would graduate on Law, afterwards at the age of 24, he would finish his graduation and move to Berlin to graduate on political science, upon his return in Athens at the age of 30, he would take political activism and join the Liberal Party which was led by Eleftherios Venizelos, during the Political Instability of 1918 and 1926, Papandreou would take a strong stance and prove his loyalty to the party, this trend followed till Venizelos's resignation in the Aftermath of Kondylis's coup, Venizelos would be forced to leave the country, and he would die one year later in Paris, in 1931 following the Republican Coup led by Liberal Officers, Papandreou would split from the Liberal Party as he opposed some ideas of Themistoklis Sofoulis, and form his own New Liberal Union, which included many deserters of the Liberal Party and other liberal likeminded people, his influental speeches and his political activism towards the left gave him the nickname "Friend of the Poor Worker", and he would win the 1932 elections with a decisive victory, getting 34% of the votes and making a government majority.

**Comment by oplo6** [comment]
![1930](https://github.com/Kaiserreich/Kaiserreich-Research-Assistance-Programme/assets/164667869/5693ee79-2393-4b03-95fa-f946868f88ef)
This is a picture of him taken in the 1930

**Comment by ihategre** [comment]
![Europeana eu-122-https___www_searchculture_gr_aggregator_edm_ELIA_000100_22_451657-ac835709013c54497563303c3aeb1c43](https://github.com/Kaiserreich/Kaiserreich-Research-Assistance-Programme/assets/74469774/049862b3-328b-46c6-9532-7b8584d3c6d6)

[source](https://www.europeana.eu/el/item/122/https___www_searchculture_gr_aggregator_edm_ELIA_000100_22_451657)

The picture above is actually from 1920, this one is from 1935.

**Comment by mpekios723** [comment]
Yeah sure but I hope you guys are able to use my description because as of now Greek potraits lack descriptions
