### ISSUE TITLE
Arne Sørensen - DEN (Denmark)

### ISSUE THREAD

**Issue by BestestIffers** [Kaiserreich/Kaiserreich-Research-Assistance-Programme#36]
https://en.wikipedia.org/wiki/Arne_S%C3%B8rensen_(politician)

Looking for the politician above, so care not to present images of the same-name Footballer.
![Arne_Sorensen](https://github.com/Kaiserreich/Kaiserreich-Research-Assistance-Programme/assets/84541896/a004c641-2029-4687-97c5-a4e7d4c2c954)

**Comment by JustOrangeFella** [comment]
![Sorensen (1)](https://github.com/Kaiserreich/Kaiserreich-Research-Assistance-Programme/assets/112580581/9885c214-27cd-4b94-806a-77d31572ada9)

Not the best but it at least is his front profile. Found it via wayback machine and am working on getting the original source

If you've already seen that one and/or it's no good then sorry, I'll be in Copenhagen soon and will have plenty of time during the days so happy to check out museums or libraries if that can be of any use:)

**Comment by retiredlt24** [comment]
https://samlinger.natmus.dk/fhm/asset/270650
A very high-res photo of him(though undated) can be found here

**Comment by Blackleafx** [comment]
Already sent em on discord but I will toss in these two as well. 
![image](https://github.com/Kaiserreich/Kaiserreich-Research-Assistance-Programme/assets/42992351/89433133-3e9a-4edf-844c-9b2cae7f6eb6)
https://nielsbirgerdanielsen.dk/frihedsraads-medlem-svaermede-for-foererprincippet-i-1930erne/

![image](https://github.com/Kaiserreich/Kaiserreich-Research-Assistance-Programme/assets/42992351/85c93adb-21fc-45ec-a238-df4202aa83c7)
https://arkiv.dk/vis/6859908 the latter is explicitly dated 1944 giving us a decent look at his appearance around that time
