### ISSUE TITLE
Vladimin von Manstein (Владимир Владимирович фон Манштейн) RUS - Russia

### ISSUE THREAD

**Issue by Sh1rako** [Kaiserreich/Kaiserreich-Research-Assistance-Programme#39]
finding photos for this guy has been something of a side project of mine over the years, unfortunately, I've only found luck in finding different versions of the same photograph. If any Russian brothers would be interested in a project that would help satisfy my desire for a new portrait for this individual, I'd be exceptionally grateful.

Here's what I've got;

![image](https://github.com/Kaiserreich/Kaiserreich-Research-Assistance-Programme/assets/44328623/a52628d5-d984-4798-97b5-31c2a82d3c6e)
![image](https://github.com/Kaiserreich/Kaiserreich-Research-Assistance-Programme/assets/44328623/5085b1fa-f92a-45ae-bebe-cbdc8361ab15)

Preferably, I would like other options besides different versions of these two photos, so if anyone can find a different angle of him, it'd go a long way. Thanks.

**Comment by Blackleafx** [comment]
This Russian forum had a few photos of him get posted:
https://sammler.ru/index.php?/topic/113657-%D0%BC%D0%B0%D0%BD%D1%88%D1%82%D0%B5%D0%B9%D0%BD/

![image](https://github.com/Kaiserreich/Kaiserreich-Research-Assistance-Programme/assets/42992351/bd46f31b-ef3d-4fab-bde9-c46a88a9ce4a)
![image](https://github.com/Kaiserreich/Kaiserreich-Research-Assistance-Programme/assets/42992351/fda2d14b-2fec-49c7-9dd6-8b1c6ff9fdb9)
Standing next to his dad in these ones (taken around 1922?)

![image](https://github.com/Kaiserreich/Kaiserreich-Research-Assistance-Programme/assets/42992351/0837287e-cd92-40e2-932a-c604e6e22c28)
Somewhere in the middle here.

**Comment by thechtoto** [comment]
From this (https://rodina-history.ru/2016/11/07/rodina-manshtejn.html) Russian article on him:
![image](https://github.com/Kaiserreich/Kaiserreich-Research-Assistance-Programme/assets/113177571/4cd579f7-2bfb-4005-8afe-d05c0b61e456)
1922, Manstein in the middle

**Comment by Sh1rako** [comment]
Holy shit, what a pull. Thank you!
