### ISSUE TITLE
Usievalad Ihnatoŭski (Усевалад Макаравіч Ігнатоўскі) - WHR (White Ruthenia/Belarus)

### ISSUE THREAD

**Issue by Sh1rako** [Kaiserreich/Kaiserreich-Research-Assistance-Programme#9]
Extremely little on this fella here, I'd be super curious to see if we could find anything more substantive. 

Known sources are listed below, there are a couple of others out there that are just variants of the same photo, but all are lower quality to my knowledge. If you find higher-quality versions of these same sources, though, please feel free to send them our way. 
![image](https://github.com/Kaiserreich/Kaiserreich-Research-Assistance-Programme/assets/44328623/71d83c9e-b615-4b98-b90f-4f23d59ba6b5)
![image](https://github.com/Kaiserreich/Kaiserreich-Research-Assistance-Programme/assets/44328623/e0b4aeab-834b-4f9a-879e-f23652f631fb)
![image](https://github.com/Kaiserreich/Kaiserreich-Research-Assistance-Programme/assets/44328623/9859e373-dd5d-43e9-8242-45b3a1151c50)
![image](https://github.com/Kaiserreich/Kaiserreich-Research-Assistance-Programme/assets/44328623/32eab0a8-d567-4b64-9b50-17a8cd2242b2)
![image](https://github.com/Kaiserreich/Kaiserreich-Research-Assistance-Programme/assets/44328623/81dd7ae8-ffcb-432b-bcc8-76de023d5854)

**Comment by Luki1223PL** [comment]
I've managed to find a few in higher quality.
![1 in higher quality (Wikipedia BE article)](https://github.com/Kaiserreich/Kaiserreich-Research-Assistance-Programme/assets/164225798/5257d078-e480-4994-891b-0cc84ce485bf)

![5 in higher quality (YT Video)](https://github.com/Kaiserreich/Kaiserreich-Research-Assistance-Programme/assets/164225798/230d68ae-d5f3-47a5-8318-d4be32408282)
https://www.youtube.com/watch?v=VvPcOBadUww

**Comment by LvovMsk** [comment]
Last Source with better lighting, but worse details
![Screenshot 2024-03-20 at 20-41-01 Усевалад Ігнатоўскі Брыгадзін П І    Интересный контент в группе Краткая история Беларуси за последнюю 1000 лет](https://github.com/Kaiserreich/Kaiserreich-Research-Assistance-Programme/assets/104763828/03b67f39-126f-4fc8-bdd4-408f947754ad)

**Comment by TheRealVladimirLemon** [comment]
![фото1 -В М Игнатовский](https://github.com/Kaiserreich/Kaiserreich-Research-Assistance-Programme/assets/90009369/bc5e33eb-6472-4e66-8b57-a5ce58b70c1a)
The grind never stops, you really thought I was gonna let the community have all the fun? Merry christmas
